
CREATE TABLE TELEGRAF_METRIC_SETTINGS 
(
    SERIES_NAME  VARCHAR (100 )PRIMARY KEY,
    QUERY          VARCHAR (4000 )NOT NULL,
    TAGS         VARCHAR (1024 )NULL,
    FIELDS       VARCHAR (1024 )NULL,
    PIVOT_KEY    VARCHAR (100 )NULL,
    PIVOT        INT NOT NULL DEFAULT 0 
);

CREATE TABLE TELEGRAF_GLOBAL_SETTINGS 
(
  SETTING_KEY VARCHAR(100)  PRIMARY KEY, 
  SETTING_VALUE INT NOT NULL 
);

-- TELEGRAF_GLOBAL_SETTINGS
INSERT INTO TELEGRAF_GLOBAL_SETTINGS VALUES ( 'CLUSTER_MODE', 0);

-- TELEGRAF_METRIC_SETTINGS 
INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_session_stat', 
       'SELECT * FROM MONITOR_SESSION_STAT',
       'GROUP_NAME|MEMBER_NAME',
       'TOTAL_SESSION_COUNT|ACTIVE_SESSION_COUNT|TOTAL_STATEMENT_COUNT|LONG_RUNNING_STATEMENT_COUNT|TOTAL_TRANSACTION_COUNT|LONG_RUNNING_TRANSACTION_COUNT', 
       NULL, 
       0
FROM DUAL ;  

INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_instance_stat', 
       'SELECT * FROM MONITOR_INSTANCE',
       'GROUP_NAME|MEMBER_NAME',
       'RELEASE_VERSION|STARTUP_TIME|INSTANCE_STATUS', 
       NULL, 
       0
FROM DUAL ;  

INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_sql_stat', 
       'SELECT * FROM MONITOR_SQL_STAT',
       'GROUP_NAME|MEMBER_NAME',
       'STAT_VALUE', 
       'STAT_NAME', 
       1
FROM DUAL ;  



INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_cluster_dispatcher_stat', 
       'SELECT * FROM MONITOR_CLUSTER_DISPATCHER',
       'GROUP_NAME|MEMBER_NAME|DISPATCHER_TYPE',
       'RX_BYTES|TX_BYTES|RX_JOBS|TX_JOBS', 
       NULL,
       0
FROM DUAL ;  

INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_tablespace_stat', 
       'SELECT * FROM MONITOR_TABLESPACE_STAT',
       'GROUP_NAME|MEMBER_NAME|NAME',
       'TOTAL_BYTES|USED_BYTES|USED_PCT', 
       NULL,
       0
FROM DUAL ;  


INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_ager_stat', 
       'SELECT * FROM MONITOR_AGER_STAT',
       'GROUP_NAME|MEMBER_NAME',
       'GLOBAL_GAP|DOMAIN_GAP|LOCAL_GAP', 
       NULL,
       0
FROM DUAL ;  

INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_session_detail', 
       'SELECT * FROM MONITOR_SESSION_DETAIL',
       'GROUP_NAME|MEMBER_NAME|SESSION_ID',
       'SERIAL_NO|TRANS_ID|CONNECTION_TYPE|USER_NAME|PROCESS_ID|LOGON_TIME|PROGRAM_NAME|CLIENT_ADDRESS|CLIENT_PORT|IS_ACTIVE', 
       NULL,
       0
FROM DUAL ;  



INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_statement_detail', 
       'SELECT * FROM MONITOR_STATEMENT_DETAIL',
       'GROUP_NAME|MEMBER_NAME|SESSIONS_STMT_ID',
       'PROGRAM_NAME|PROCESS_ID|STATUS|SQL_TEXT|ELASPED_SECONDS', 
       NULL,
       0
FROM DUAL ;  



INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_transaction_detail', 
       'SELECT * FROM MONITOR_TRANSACTION_DETAIL',
       'GROUP_NAME|MEMBER_NAME|TRANS_ID',
       'PROGRAM_NAME|PROCESS_ID|TRANS_STATE|IS_XA|ELAPSED_SECONDS|WAIT_FOR', 
       NULL,
       0
FROM DUAL ;  

INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_sga_stat', 
       'SELECT * FROM MONITOR_SGA_STAT',
       'GROUP_NAME|MEMBER_NAME',
       'TOTAL_BYTES|USED_BYTES|USED_PCT', 
       NULL,
       0
FROM DUAL ;  

INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_shard_table_distibution', 
       'SELECT * FROM MONITOR_SHARD_TAB_DISTRIBUTION',
       'OWNER|TABLE_SCHEMA|TABLE_NAME|GROUP_NAME',
       'ALLOC_BYTES', 
       NULL,
       0
FROM DUAL ;  

INSERT INTO TELEGRAF_METRIC_SETTINGS 
SELECT 'goldilocks_shard_index_distibution', 
       'SELECT * FROM MONITOR_SHARD_IND_DISTRIBUTION',
       'OWNER|TABLE_SCHEMA|TABLE_NAME|INDEX_NAME|GROUP_NAME',
       'ALLOC_BYTES', 
       NULL,
       0
FROM DUAL ;  

